Add new configuration to do nothing if dist file is absent
sroze/companienv pull request #16
Opened 2018-07-16 08:38 UTC by roukmoute

Currently, our production is runned without a .env.  
All is in the current environment variables.

So in production mode, we do not want to run this plugin.

2018-07-16 08:40 UTC, sroze commented
But if you do this... in development the plugin won't run either, right? 🤔

2018-07-16 08:43 UTC, roukmoute commented
Of course !
I must check if the file exist.

But I don't like the name of this option, do you have any suggestion?

`ignore-dist-file-if-not-exist`?! :trollface:

2018-07-16 08:46 UTC, sroze commented
Let's rewind. Why don't you want the plugin to run in production? Because AFAIK, you will load the `.env` file only if your environment variables are not already defined, right? For example, Symfony will not load the `.env` file if the `APP_ENV` environment variable is already defined.

2018-07-16 09:19 UTC, roukmoute commented
So you prefer I use an equivalent like Symfony?
I remove option and use only anything like `$_SERVER['APP_ENV']`.

2018-07-18 08:00 UTC, roukmoute commented
Up @sroze

2018-07-18 08:06 UTC, sroze commented
What I meant was... why do you care if this script is run when your application won't use the `.env` file that was generated? 🤔

2018-07-19 08:22 UTC, sroze requested changes

2018-07-19 08:22 UTC, sroze commented on src/Companienv/Composer/InteractionViaComposer.php
> +use function sprintf;
I don't think you need this 🤔

2018-07-19 08:22 UTC, sroze commented on src/Companienv/Composer/InteractionViaComposer.php
> +            $this->writeln(sprintf('Automatically returned %s in non-interactive mode', $default));
Can you add quotes (`"`) around `%s`?

2018-07-19 08:30 UTC, roukmoute commented on src/Companienv/Composer/InteractionViaComposer.php
> +use function sprintf;
Adding this speed up resolving.

2018-07-19 13:47 UTC, sroze commented
Thank you @roukmoute.

2018-07-19 13:47 UTC, merged